### ISSUE TITLE
Almost all of my extensions are failing after the release of 1210.12.104.1000

### ISSUE THREAD

**Issue by aarsan** [chef-partners/azure-chef-extension#148]
New-AzureRmResourceGroupDeployment : 11:27:09 AM - Handler 'Chef.Bootstrap.WindowsAzure.ChefClient' has reported failure for VM Extension 'ChefExtension' with terminal error code '1007' and error
message: 'Install failed for plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version 1210.12.104.1000) with exception Command
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.104.1000\install.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...'

------------------------------------------

Even when I was on 103, I would get this error about 10% of the time but it appears to be almost every bootstrap now.

**Comment by aarsan** [comment]
Here is some more information from the waagent logs:

[06/20/2016 22:20:45.84] [INFO]  Waiting for command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.104.1000\install.cmd
[06/20/2016 22:35:48.86] [ERROR] Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.104.1000\install.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...
[06/20/2016 22:35:48.86] [WARN]  Install failed for plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version 1210.12.104.1000) with exception Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.104.1000\install.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it..., Code: 1007
[06/20/2016 22:35:48.89] [ERROR] Error while processing plugin Chef.Bootstrap.WindowsAzure.ChefClient version 1210.12.104.1000, state: enabled, error: System.Exception: Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.104.1000\install.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.InvokeCommand(String command, PluginArtifacts pluginArtifact, String pluginVersion, String pluginFolder, String pluginLogFolder, Int32 processWaitTimeout, PluginEventType startType, PluginEventType endType)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.InstallHandler(PluginArtifacts artifact)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.StartHandlerStateMachine(PluginArtifacts data, RDConfigHostingEnvironmentSettingsPlugin plugin)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.PluginInstaller.PluginBackgroundThread(Object sender, DoWorkEventArgs e)

**Comment by Aliasgar16** [comment]
@aarsan can you please share `CommandExecution*.log` log files from the following path:
`C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.104.1000` ?

**Comment by Aliasgar16** [comment]
@aarsan can you also share the value of `autoUpdateClient`, `uninstallChefClient` and `deleteChefConfig` from `0.settings` file which is present at the following path:
`C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.104.1000\RuntimeSettings` ?

**Comment by Vasu1105** [comment]
@aarsan  can you also let us know what tool you are using for installing new version of extension and what command you are executing ?

**Comment by Vasu1105** [comment]
@aarsan Please provide us the details so that we will try to reproduce this issue and resolve it from our side.

**Comment by NimishaS** [comment]
@aarsan if this issue relates to https://github.com/chef-partners/azure-chef-extension/issues/114, it should be resolved.
Please let us know.
