### ISSUE TITLE
ReferenceError: log is not defined

### ISSUE THREAD

**Issue by matkam** [chef-partners/azure-chef-extension#180]
I'm trying to add the chef extension using cli:
```/usr/local/bin/azure vm extension set-chef MyNet my-vm-id --run-list=role[some_role] --validation-pem=/Users/matt/.chef/validator.pem --bootstrap-options={"chef_node_name":"my-vm-id","chef_server_url":"https://api.opscode.com/organizations/myorg","validation_client_name":"validator"} --client-config=/path/to/chef-repo/config/client.rb```
I'm getting:
```
info:    Executing command vm extension set-chef
+ Looking up the VM "crawler-az-grau53sq91ud"                                  
+ Getting virtual machine extension image verions (Publisher: "Chef.Bootstrap.WindowsAzure" Type:"LinuxChefClient" Location:"westus")
error:   log is not defined
error:   Error information has been recorded to /Users/matt/.azure/azure.err
error:   vm extension set-chef command failed
```

azure.err files shows:
```
2016-12-07T00:40:38.443Z:
{ ReferenceError: log is not defined
  <<< async stack >>>
    at setChefExtension__28 (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient._js:1890:31)
  at __30 (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vm._js:641:18)
  <<< raw stack >>>
    at __$setChefExtension__28 (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient._js:1890:31)
    at /usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:169:5
    at Object.flush (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:24:29)
    at ___ (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:123:61)
    at /usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/azure-arm-compute/lib/operations/virtualMachineExtensionImages.js:535:12
    at retryCallback (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/util/utils.js:587:7
    at handleRedirect (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/util/utils.js:564:9)
    at /usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/util/logging.js:339:7

  stack: [Getter],
  __frame:
   { name: '__30',
     line: 637,
     file: '/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vm._js',
     prev: undefined,
     calls: 1,
     active: false,
     offset: 4,
     col: 17 },
  rawStack: [Getter] }
ReferenceError: log is not defined
  <<< async stack >>>
    at setChefExtension__28 (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient._js:1890:31)
  at __30 (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vm._js:641:18)
  <<< raw stack >>>
    at __$setChefExtension__28 (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/commands/arm/vm/vmClient._js:1890:31)
    at /usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:169:5
    at Object.flush (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:24:29)
    at ___ (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/streamline/lib/callbacks/runtime.js:123:61)
    at /usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/azure-arm-compute/lib/operations/virtualMachineExtensionImages.js:535:12
    at retryCallback (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/exponentialRetryPolicyFilter.js:140:9)
    at handleRedirect (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/node_modules/ms-rest/lib/filters/redirectFilter.js:36:9)
    at /usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/util/utils.js:587:7
    at handleRedirect (/usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/util/utils.js:564:9)
    at /usr/local/Cellar/azure-cli/0.10.7/libexec/lib/node_modules/azure-cli/lib/util/logging.js:339:7
```

I'm sure something changed because this used to work before updating the CLI tools. Am I missing something?

**Comment by NimishaS** [comment]
@matkam I tried the following commands with `azure cli v0.10.4` and both worked successfully for me:

**Comment by NimishaS** [comment]
@matkam , any updates here?

**Comment by matkam** [comment]
@NimishaS I removed ```log_location``` from my client.rb file, and the command works now. Thanks!
