### ISSUE TITLE
Intermittent Chef Extension Timeout on Standard_DS2_v2

### ISSUE THREAD

**Issue by sean-horn** [chef-partners/azure-chef-extension#230]
We are getting intermittent Chef Extension timeouts on version 1210.12.109.1005 while trying to provision Standard_DS2_v2 sized Azure nodes.

Can we provide more debugging information?
Is there some reason the extension would be delayed, resulting in `Another msi install is in progress`? Is there a way to possibly work around this issue?

System type:

```
"vmSize": "Standard_DS2_v2",
"imagePublisher": "MicrosoftWindowsServer",
"imageOffer": "WindowsServer",
"imageSku": "2012-R2-Datacenter", 
```

Failure messages:

```
[09/12/2017 16:52:47.70] Executing: C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\enable.cmd
[09/12/2017 16:55:03.93] Execution Complete.
######
Execution Output:
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>set CHEF_EXT_DIR=C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>echo C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>REM Installing chef-client
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>powershell -nologo -noprofile -executionpolicy unrestricted Import-Module C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\bin\chef-install.psm1;Install-ChefClient
Environment variables not passed.
Downloading Chef Client ...
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        Omnitruck                           {Get-ProjectMetada...
Installing chef from C:\Windows\TEMP\chef-client-13.3.42-1-x64.msi
Another msi install is in progress (exit code 1618), retrying (1)...
Another msi install is in progress (exit code 1618), retrying (2)...
Another msi install is in progress (exit code 1618), retrying (3)...
Another msi install is in progress (exit code 1618), retrying (4)...
Another msi install is in progress (exit code 1618), retrying (5)...
Another msi install is in progress (exit code 1618), retrying (6)...
Another msi install is in progress (exit code 1618), retrying (7)...
Another msi install is in progress (exit code 1618), retrying (8)...
[09/12/2017 16:54:52] Installing Azure-Chef-Extension gem
[09/12/2017 16:55:00] Installed Azure-Chef-Extension gem successfully
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>set path=C:\opscode\chef\bin;C:\opscode\chef\embedded\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>ruby C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\bin\chef-enable.rb


Execution Error:
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ rb_sysopen - C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/azure-chef-extension-0.0.1/spec/functional/secret_key_spec.rb
C:/opscode/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- chef/azure/commands/enable (LoadError)
        from C:/opscode/chef/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Packages/Plugins/Chef.Bootstrap.WindowsAzure.ChefClient/1210.12.109.1005/bin/chef-enable.rb:4:in `<main>'

######
Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: 1
```

Success messages:

```
[09/12/2017 16:51:53.48] Executing: C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\install.cmd
[09/12/2017 16:52:07.66] Execution Complete.
######
Execution Output:
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>set CHEF_EXT_DIR=C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>echo C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>REM Moved the installation steps into enable phase for windows
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>REM Because n.settings file is not available during install phase.
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>REM We need to read some values like bootstrap_version(chef-client version)
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>REM And daemon from n.settings during install
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>REM Doing required settings if Powershell Version is less than 3
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005>powershell -nologo -noprofile -executionpolicy unrestricted Import-Module C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\bin\shared.ps1;Run-Powershell2-With-Dot-Net4


Execution Error:

######
Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.109.1005\install.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: 0
Plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version: 1210.12.109.1005) completed successfully.
```

**Comment by bcolebank** [comment]
I was able to get it to work by adding an additional depends on to the extensions to force them to install in a specific order:
 
Monitoring waits on the Diagnostics to install:
          "type": "extensions",
          "name": "Microsoft.EnterpriseCloud.Monitoring",
          "apiVersion": "[variables('monitoringApiVersion')]",
          "location": "[resourceGroup().location]",
          "dependsOn": [
            "[concat('Microsoft.Compute/virtualMachines/', parameters('vmName'))]",
            "[concat('Microsoft.Compute/virtualMachines/', parameters('vmName'), '/extensions/Microsoft.Insights.VMDiagnosticsSettings')]"
          ],
Chef waits on Monitoring:
      "name": "[concat(parameters('vmName'), '-Chef-Deployment')]",
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "[variables('extensionApiVersion')]",
      "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', parameters('vmName'))]",
        "[concat('Microsoft.Compute/virtualMachines/', parameters('vmName'), '/extensions/Microsoft.EnterpriseCloud.Monitoring')]"
      ],

If I add more extensions, then I have to manage the install order, or just have Chef install the rest, but it appears to be working for me now.

**Comment by Vasu1105** [comment]
Closing this issue due to age.
