### ISSUE TITLE
Azure extension failures on provisioning

### ISSUE THREAD

**Issue by amarkulis** [chef-partners/azure-chef-extension#241]
We frequently run into the error below deploying servers.

[12/07/2017 11:43:23.62] Executing: C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1000\enable.cmd 
[12/07/2017 11:48:23.71] Execution Complete.
######
Execution Output:
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1000>set CHEF_EXT_DIR=C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1000\ 
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1000>echo C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1000\ 
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1000\
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1000>REM Installing chef-client 
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1000>powershell -nologo -noprofile -executionpolicy unrestricted Import-Module C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1000\bin\chef-install.psm1;Install-ChefClient 
Environment variables not passed.
Downloading Chef Client ...
ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Script     0.0        Omnitruck                           {Get-ProjectMetada...
Installing chef from D:\TEMP\chef-client-12.18.31-1-x64.msi

Execution Error:

######
Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1000\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...

**Comment by dheerajd-msys** [comment]
@amarkulis Could you please let us know which command you tried out to provision the vm? 
I've tried out `knife-azure ARM` but issue is not reproduced on `2012-R2-Datacenter`. Please let us know which windows you are trying to create.

Please try again with below command and let us know the output
```
PS D:\Chef_Repo\knife-azure> bundle exec knife azurerm server create  --azure-resource-group-name dhdevelopment2 --azure-vm-name dhwinarm2 --azure-service-location 'eastus` --azure-image-os-type windows  -x azureuser -P azure@123456 --azure-vnet-name default-vnet --azure-vnet-subnet-name default_subnet -c D:\chef-starter\chef-repo\.chef\knife.rb 
```
**OUTPUT**
[06/18/2018 09:43:54.20] Executing: C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\enable.cmd 
[06/18/2018 09:44:18.26] Execution Complete.
######
Execution Output:
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001>set CHEF_EXT_DIR=C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\ 
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001>echo C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\ 
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001>REM Installing chef-client 
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001>powershell -nologo -noprofile -executionpolicy unrestricted Import-Module C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\bin\chef-install.psm1;Install-ChefClient 
Environment variables not passed.
Downloading Chef Client ...
[06/18/2018 09:44:01] Installing Azure-Chef-Extension gem
Successfully installed azure-chef-extension-0.0.1
1 gem installed
[06/18/2018 09:44:06] Installed Azure-Chef-Extension gem successfully
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001>set path=C:\opscode\chef\bin;C:\opscode\chef\embedded\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\opscode\chef\bin\ 
C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001>ruby C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\bin\chef-enable.rb 
2018-06-18 09:44:18 +0000 extension_root --> C:/Packages/Plugins/Chef.Bootstrap.WindowsAzure.ChefClient/1210.12.110.1001
2018-06-18 09:44:18 +0000 Creating EnableChef object with []...
2018-06-18 09:44:18 +0000 Running Chef extension enable command...
Logging status message: chef-extension enabled
2018-06-18 09:44:18 +0000 Getting chef-client service status
2018-06-18 09:44:18 +0000 chef-client service is already installed.
2018-06-18 09:44:18 +0000 checking if chef-client service interval has been changed by the user...
2018-06-18 09:44:18 +0000 no..chef-client service interval has not been changed by the user..exiting.
Logging status message: chef-service enabled


Execution Error:

######
Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: 0
Plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version: 1210.12.110.1001) completed successfully.

**Comment by bcolebank** [comment]
On my latest failure of this type, I pulled this error from C:\WindowsAzure\Logs\WaAppAgent.txt:
[00000014] [08/13/2018 10:24:12.96] [INFO]  Start Workflow.
[00000014] [08/13/2018 10:24:12.96] [INFO]  Starting installation/update of plugins. Incarnation: 4, extension count: 3
[00000014] [08/13/2018 10:24:12.96] [WARN]  Start the root task for Plugin handler 'Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent' Runtime Settings of extension ''.
[00000014] [08/13/2018 10:24:12.96] [WARN]  Start the root task for Plugin handler 'Microsoft.Azure.Diagnostics.IaaSDiagnostics' Runtime Settings of extension ''.
[00000014] [08/13/2018 10:24:12.96] [WARN]  Start the root task for Plugin handler 'Chef.Bootstrap.WindowsAzure.ChefClient' Runtime Settings of extension ''.
[00000013] [08/13/2018 10:24:12.96] [INFO]  Starting extension processing for extension 'HandlerName: 'Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent', ExtensionName: '''
[00000013] [08/13/2018 10:24:12.96] [WARN]  Processing plugin Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent version 1.0.11081.5, state: enabled, autoupgrade: True, isJson: True
[00000014] [08/13/2018 10:24:12.96] [INFO]  Starting extension processing for extension 'HandlerName: 'Chef.Bootstrap.WindowsAzure.ChefClient', ExtensionName: '''
[00000014] [08/13/2018 10:24:12.96] [WARN]  Processing plugin Chef.Bootstrap.WindowsAzure.ChefClient version 1210.12.110.1001, state: enabled, autoupgrade: False, isJson: True
[00000005] [08/13/2018 10:24:12.96] [INFO]  Starting extension processing for extension 'HandlerName: 'Microsoft.Azure.Diagnostics.IaaSDiagnostics', ExtensionName: '''
[00000005] [08/13/2018 10:24:12.97] [WARN]  Processing plugin Microsoft.Azure.Diagnostics.IaaSDiagnostics version 1.11.3.12, state: enabled, autoupgrade: True, isJson: True
[00000013] [08/13/2018 10:24:13.22] [INFO]  JSON manifest file C:\Packages\Plugins\Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent\1.0.11081.5\HandlerManifest.json found corresponding to the plugin Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent
[00000013] [08/13/2018 10:24:13.26] [INFO]  JSON manifest file C:\Packages\Plugins\Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent\1.0.11081.5\HandlerManifest.json found corresponding to the plugin Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent
[00000013] [08/13/2018 10:24:13.26] [WARN]  Process runtime settings of plugin (handler name: Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent, extension name: , version: 1.0.11081.5)., Code: 0
[00000013] [08/13/2018 10:24:13.26] [INFO]  Validating RuntimeSettings for the Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent plugin (version 1.0.11081.5).
[00000013] [08/13/2018 10:24:13.26] [WARN]  Writing runtime settings for the Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent plugin (version 1.0.11081.5).
[00000013] [08/13/2018 10:24:13.26] [INFO]  RuntimeSettings found for the Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent plugin (version 1.0.11081.5).
[00000005] [08/13/2018 10:24:13.22] [INFO]  JSON manifest file C:\Packages\Plugins\Microsoft.Azure.Diagnostics.IaaSDiagnostics\1.11.3.12\HandlerManifest.json found corresponding to the plugin Microsoft.Azure.Diagnostics.IaaSDiagnostics
[00000005] [08/13/2018 10:24:13.26] [INFO]  JSON manifest file C:\Packages\Plugins\Microsoft.Azure.Diagnostics.IaaSDiagnostics\1.11.3.12\HandlerManifest.json found corresponding to the plugin Microsoft.Azure.Diagnostics.IaaSDiagnostics
[00000013] [08/13/2018 10:24:13.32] [INFO]  Writing runtime settings to temp file C:\Packages\Plugins\Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent\1.0.11081.5\RuntimeSettings\0.settings.tmp succeeded.
[00000013] [08/13/2018 10:24:13.32] [WARN]  Provided runtime settings to the Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent plugin (version 1.0.11081.5) in C:\Packages\Plugins\Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent\1.0.11081.5\RuntimeSettings\0.settings file.
[00000013] [08/13/2018 10:24:13.32] [INFO]  Writing default status file C:\Packages\Plugins\Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent\1.0.11081.5\Status\0.status for the Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent handler (version 1.0.11081.5)
[00000013] [08/13/2018 10:24:13.32] [INFO]  Not overwriting status file C:\Packages\Plugins\Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent\1.0.11081.5\Status\0.status with default content for the Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent handler (version 1.0.11081.5)
[00000013] [08/13/2018 10:24:13.33] [WARN]  Enabling plugin (handler name: Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent, extension name: , version: 1.0.11081.5)., Code: 0
[00000013] [08/13/2018 10:24:13.33] [WARN]  Staring a process with the launch command C:\Packages\Plugins\Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent\1.0.11081.5\MMAExtensionEnable.exe and params: 
[00000013] [08/13/2018 10:24:13.33] [INFO]  Beginning enable of plugin Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent.
[00000014] [08/13/2018 10:24:13.35] [WARN]  Setting the install state of the handler Chef.Bootstrap.WindowsAzure.ChefClient_1210.12.110.1001 to NotInstalled
[00000014] [08/13/2018 10:24:13.35] [WARN]  Downloading plugin package (name: Chef.Bootstrap.WindowsAzure.ChefClient, version: 1210.12.110.1001)., Code: 0
[00000014] [08/13/2018 10:24:13.35] [INFO]  Plugin Chef.Bootstrap.WindowsAzure.ChefClient 1210.12.110.1001 not found in cache.
[00000014] [08/13/2018 10:24:13.38] [INFO]  Starting download of plugin Chef.Bootstrap.WindowsAzure.ChefClient from location: https://zrdfepirv2bn4prdstr02.blob.core.windows.net/0fa68ca509a643f49117169ef78baf70/Chef.Bootstrap.WindowsAzure__ChefClient__1210.12.110.1001.
[00000013] [08/13/2018 10:24:13.91] [INFO]  Waiting for command C:\Packages\Plugins\Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent\1.0.11081.5\MMAExtensionEnable.exe of plugin (name Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent version 1.0.11081.5) to finish...
[00000005] [08/13/2018 10:24:13.91] [WARN]  Process runtime settings of plugin (handler name: Microsoft.Azure.Diagnostics.IaaSDiagnostics, extension name: , version: 1.11.3.12)., Code: 0
[00000014] [08/13/2018 10:24:13.94] [INFO]  Download finished for plugin Chef.Bootstrap.WindowsAzure.ChefClient.
[00000014] [08/13/2018 10:24:14.54] [WARN]  Extracting plugin package (name: Chef.Bootstrap.WindowsAzure.ChefClient, version: 1210.12.110.1001)., Code: 0
[00000014] [08/13/2018 10:24:14.54] [INFO]  Extracting plug-in zip file to folder. Zip file: C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\Chef.Bootstrap.WindowsAzure.ChefClient_1210.12.110.1001.zip
[00000005] [08/13/2018 10:24:14.54] [INFO]  Validating RuntimeSettings for the Microsoft.Azure.Diagnostics.IaaSDiagnostics plugin (version 1.11.3.12).
[00000005] [08/13/2018 10:24:14.55] [WARN]  Writing runtime settings for the Microsoft.Azure.Diagnostics.IaaSDiagnostics plugin (version 1.11.3.12).
[00000005] [08/13/2018 10:24:14.55] [INFO]  RuntimeSettings found for the Microsoft.Azure.Diagnostics.IaaSDiagnostics plugin (version 1.11.3.12).
[00000005] [08/13/2018 10:24:14.66] [INFO]  Writing runtime settings to temp file C:\Packages\Plugins\Microsoft.Azure.Diagnostics.IaaSDiagnostics\1.11.3.12\RuntimeSettings\0.settings.tmp succeeded.
[00000005] [08/13/2018 10:24:14.73] [WARN]  Provided runtime settings to the Microsoft.Azure.Diagnostics.IaaSDiagnostics plugin (version 1.11.3.12) in C:\Packages\Plugins\Microsoft.Azure.Diagnostics.IaaSDiagnostics\1.11.3.12\RuntimeSettings\0.settings file.
[00000005] [08/13/2018 10:24:14.73] [INFO]  Writing default status file C:\Packages\Plugins\Microsoft.Azure.Diagnostics.IaaSDiagnostics\1.11.3.12\Status\0.status for the Microsoft.Azure.Diagnostics.IaaSDiagnostics handler (version 1.11.3.12)
[00000005] [08/13/2018 10:24:14.73] [INFO]  Not overwriting status file C:\Packages\Plugins\Microsoft.Azure.Diagnostics.IaaSDiagnostics\1.11.3.12\Status\0.status with default content for the Microsoft.Azure.Diagnostics.IaaSDiagnostics handler (version 1.11.3.12)
[00000005] [08/13/2018 10:24:14.73] [WARN]  Enabling plugin (handler name: Microsoft.Azure.Diagnostics.IaaSDiagnostics, extension name: , version: 1.11.3.12)., Code: 0
[00000005] [08/13/2018 10:24:14.73] [WARN]  Staring a process with the launch command C:\Packages\Plugins\Microsoft.Azure.Diagnostics.IaaSDiagnostics\1.11.3.12\DiagnosticsPluginLauncher.exe and params: 
[00000005] [08/13/2018 10:24:14.73] [INFO]  Beginning enable of plugin Microsoft.Azure.Diagnostics.IaaSDiagnostics.
[00000005] [08/13/2018 10:24:15.09] [INFO]  Waiting for command C:\Packages\Plugins\Microsoft.Azure.Diagnostics.IaaSDiagnostics\1.11.3.12\DiagnosticsPluginLauncher.exe of plugin (name Microsoft.Azure.Diagnostics.IaaSDiagnostics version 1.11.3.12) to finish...
[00000014] [08/13/2018 10:24:15.99] [WARN]  Setting up plugin environment (name: Chef.Bootstrap.WindowsAzure.ChefClient, version: 1210.12.110.1001)., Code: 0
[00000014] [08/13/2018 10:24:15.99] [INFO]  JSON manifest file C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\HandlerManifest.json found corresponding to the plugin Chef.Bootstrap.WindowsAzure.ChefClient
[00000014] [08/13/2018 10:24:15.99] [INFO]  Successfully created folder C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\RuntimeSettings
[00000014] [08/13/2018 10:24:15.99] [INFO]  Successfully created folder C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\Status
[00000014] [08/13/2018 10:24:16.01] [INFO]  Successfully created folder C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001
[00000014] [08/13/2018 10:24:16.01] [INFO]  Plugin (name Chef.Bootstrap.WindowsAzure.ChefClient, version 1210.12.110.1001) will not report heartbeat according to the manifest.
[00000014] [08/13/2018 10:24:16.01] [INFO]  JSON manifest file C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\HandlerManifest.json found corresponding to the plugin Chef.Bootstrap.WindowsAzure.ChefClient
[00000014] [08/13/2018 10:24:16.01] [WARN]  Installing plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version: 1210.12.110.1001), Code: 0
[00000014] [08/13/2018 10:24:16.01] [WARN]  Staring a process with the launch command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\install.cmd and params: 
[00000014] [08/13/2018 10:24:16.01] [INFO]  Beginning installation of plugin Chef.Bootstrap.WindowsAzure.ChefClient.
[00000014] [08/13/2018 10:24:16.05] [INFO]  Waiting for command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\install.cmd of plugin (name Chef.Bootstrap.WindowsAzure.ChefClient version 1210.12.110.1001) to finish...
[00000013] [08/13/2018 10:24:26.88] [INFO]  Command C:\Packages\Plugins\Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent\1.0.11081.5\MMAExtensionEnable.exe of Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent has exited with Exit code: 0
[00000013] [08/13/2018 10:24:26.88] [INFO]  Successfully enabled plugin Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent.
[00000013] [08/13/2018 10:24:26.90] [WARN]  Setting the install state of the handler Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent_1.0.11081.5 to Enabled
[00000013] [08/13/2018 10:24:26.90] [WARN]  Plugin enabled (handler name: Microsoft.EnterpriseCloud.Monitoring.MicrosoftMonitoringAgent, extension name: , version: 1.0.11081.5)., Code: 0
[00000014] [08/13/2018 10:24:35.06] [INFO]  Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\install.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: 0
[00000014] [08/13/2018 10:24:35.06] [INFO]  Successfully installed plugin Chef.Bootstrap.WindowsAzure.ChefClient.
[00000014] [08/13/2018 10:24:35.07] [WARN]  Installed plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version: 1210.12.110.1001), Code: 0
[00000014] [08/13/2018 10:24:35.07] [WARN]  Setting the install state of the handler Chef.Bootstrap.WindowsAzure.ChefClient_1210.12.110.1001 to Installed
[00000014] [08/13/2018 10:24:35.07] [WARN]  Process runtime settings of plugin (handler name: Chef.Bootstrap.WindowsAzure.ChefClient, extension name: , version: 1210.12.110.1001)., Code: 0
[00000014] [08/13/2018 10:24:35.07] [INFO]  Validating RuntimeSettings for the Chef.Bootstrap.WindowsAzure.ChefClient plugin (version 1210.12.110.1001).
[00000014] [08/13/2018 10:24:35.07] [WARN]  Writing runtime settings for the Chef.Bootstrap.WindowsAzure.ChefClient plugin (version 1210.12.110.1001).
[00000014] [08/13/2018 10:24:35.07] [INFO]  RuntimeSettings found for the Chef.Bootstrap.WindowsAzure.ChefClient plugin (version 1210.12.110.1001).
[00000014] [08/13/2018 10:24:35.07] [INFO]  Writing runtime settings to temp file C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\RuntimeSettings\0.settings.tmp succeeded.
[00000014] [08/13/2018 10:24:35.07] [WARN]  Provided runtime settings to the Chef.Bootstrap.WindowsAzure.ChefClient plugin (version 1210.12.110.1001) in C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\RuntimeSettings\0.settings file.
[00000014] [08/13/2018 10:24:35.07] [INFO]  Writing default status file C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\Status\0.status for the Chef.Bootstrap.WindowsAzure.ChefClient handler (version 1210.12.110.1001)
[00000014] [08/13/2018 10:24:35.09] [INFO]  Default status file C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\Status\0.status successfully written for the Chef.Bootstrap.WindowsAzure.ChefClient handler (version 1210.12.110.1001)
[00000014] [08/13/2018 10:24:35.09] [WARN]  Enabling plugin (handler name: Chef.Bootstrap.WindowsAzure.ChefClient, extension name: , version: 1210.12.110.1001)., Code: 0
[00000014] [08/13/2018 10:24:35.09] [WARN]  Staring a process with the launch command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\enable.cmd and params: 
[00000014] [08/13/2018 10:24:35.09] [INFO]  Beginning enable of plugin Chef.Bootstrap.WindowsAzure.ChefClient.
[00000014] [08/13/2018 10:24:35.12] [INFO]  Waiting for command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\enable.cmd of plugin (name Chef.Bootstrap.WindowsAzure.ChefClient version 1210.12.110.1001) to finish...
[00000005] [08/13/2018 10:25:41.65] [INFO]  Command C:\Packages\Plugins\Microsoft.Azure.Diagnostics.IaaSDiagnostics\1.11.3.12\DiagnosticsPluginLauncher.exe of Microsoft.Azure.Diagnostics.IaaSDiagnostics has exited with Exit code: 0
[00000005] [08/13/2018 10:25:41.65] [INFO]  Successfully enabled plugin Microsoft.Azure.Diagnostics.IaaSDiagnostics.
[00000005] [08/13/2018 10:25:41.65] [WARN]  Setting the install state of the handler Microsoft.Azure.Diagnostics.IaaSDiagnostics_1.11.3.12 to Enabled
[00000005] [08/13/2018 10:25:41.65] [WARN]  Plugin enabled (handler name: Microsoft.Azure.Diagnostics.IaaSDiagnostics, extension name: , version: 1.11.3.12)., Code: 0
[00000014] [08/13/2018 10:29:38.13] [ERROR] Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...
[00000014] [08/13/2018 10:29:38.13] [ERROR] Enable command of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: -2
[00000014] [08/13/2018 10:29:38.13] [ERROR] Enable failed for plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version 1210.12.110.1001) with exception Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it..., Code: 1009
[00000014] [08/13/2018 10:29:38.13] [ERROR] Error while processing plugin Chef.Bootstrap.WindowsAzure.ChefClient version 1210.12.110.1001, state: enabled, error: System.Exception: Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.InvokeCommand(String command, PluginArtifacts pluginArtifact, String pluginVersion, String pluginFolder, String pluginLogFolder, Int32 processWaitTimeout, PluginEventType startType, PluginEventType endType, CancellationToken ct)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.EnableHandler(PluginArtifacts artifact, CancellationToken ct)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.StartHandlerStateMachine(PluginArtifacts data, RDConfigHostingEnvironmentSettingsPlugin plugin, CancellationToken ct)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.PluginInstaller.ProcessPluginArtifacts(PluginArtifacts pluginArtifacts, CancellationToken ct)

**Comment by marco-junge** [comment]
I am noticing the same behavior here. Last lines from C:\WindowsAzure\Logs\WaAppAgent.txt are also 
```
[ERROR] Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...
[ERROR] Enable command of Chef.Bootstrap.WindowsAzure.ChefClient has exited with Exit code: -2
[ERROR] Enable failed for plugin (name: Chef.Bootstrap.WindowsAzure.ChefClient, version 1210.12.110.1001) with exception Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it..., Code: 1009
[ERROR] Error while processing plugin Chef.Bootstrap.WindowsAzure.ChefClient version 1210.12.110.1001, state: enabled, error: System.Exception: Command C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\enable.cmd of Chef.Bootstrap.WindowsAzure.ChefClient has not exited on time! Killing it...
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.InvokeCommand(String command, PluginArtifacts pluginArtifact, String pluginVersion, String pluginFolder, String pluginLogFolder, Int32 processWaitTimeout, PluginEventType startType, PluginEventType endType, CancellationToken ct)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.EnableHandler(PluginArtifacts artifact, CancellationToken ct)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.HandlerStateMachine.StartHandlerStateMachine(PluginArtifacts data, RDConfigHostingEnvironmentSettingsPlugin plugin, CancellationToken ct)
   at Microsoft.WindowsAzure.GuestAgent.ContainerStateMachine.PluginInstaller.ProcessPluginArtifacts(PluginArtifacts pluginArtifacts, CancellationToken ct)
```
We're deploying the chef extension with an ARM-Template with the ruby sdk. Actually almost every deployment to windows server core 2016 is failing. Connecting to VM auf executing "C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\enable.cmd" manually in console works but doesn't fit for us of course. Could you investigate here, please?

**Comment by Vasu1105** [comment]
@marco-junge Thank you for reporting. We most of the time not able to reproduce this issues because the environment in which you are working is different than what we try to reproduce the issue with. We recently experienced this that sometimes issue is reproducible only on specific region or images. So if you give us detailed information that will help us to go to the root cause of the issue.

Please provide us following details
1) The ARM template .
2) The command you are using to deploy vm
3) In which region you are deploying the VM
4) If you are using any specific image. Details of images like OS, SKU etc.
5)  All log files
The location for all logs is 
1) C:\\WindowsAzure\Logs\waagent.log
2) C:\\WindowsAzure\Logs\Plugins\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001\chef-client.log
3) CommandExection.log from above location

**Comment by marco-junge** [comment]
Thanks @Vasu1105. I attached [arm-template-and-logfiles.zip](https://github.com/chef-partners/azure-chef-extension/files/2418739/arm-template-and-logfiles.zip). 

We're deploying all arm templates with a self written provisioning cookbook. And finally it all ends up at azure sdk's [deployment.create_or_update](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_resources/lib/2018-05-01/generated/azure_mgmt_resources/deployments.rb#L850) function. Sequence is: 
1. Start with an arm template for a vm 
2. Add an access policy for the vm to one ore more keyvaults (msi)
3. Deploy the arm template for chef extension

Some further information about region and images:
- VMs are deployed exclusively in westeurope region
- OS-Image is always "2016-Datacenter-Server-Core-smalldisk"
- Storage-Type is "Standard_LRS"
- VM-Sizes are "Standard_A2_v2", "Standard_D2s_v3", "Standard_DS2_v2" and "Standard_B2ms"

**Comment by Vasu1105** [comment]
In your zip file I haven't got the chef-client.log.
Is it possible for you to try same deployments on some other region like West US ? 

Also can you check if following workarounds fix your issue
1) - Use "daemon": "task" and set "chef_daemon_interval": "30" (the default setting)
2) - Use "daemon": "none" and let your initial run list configure Chef correctly for future run

We will try to reproduce the issue with your given inputs but that might take time. Meanwhile you can try out above things.

**Comment by marco-junge** [comment]
I haven't found the chef-client.log in C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.110.1001 Folder. Only the two CommandExection*.log files. I'll give the workarounds a try and come back with more information.

**Comment by Vasu1105** [comment]
Sorry my bad yes there won't be any chef-client.log since enable.cmd is stopped in between.
My initial debug is that the chef-client installation is taking time and enable.cmd has a time limit for extension due to which the enable.cmd is getting timed out before chef-client gets installed. 

You can check changing the image size too.

**Comment by marco-junge** [comment]
> Use "daemon": "task" and set "chef_daemon_interval": "30" (the default setting)
> Use "daemon": "none" and let your initial run list configure Chef correctly for future run

Both had no influence and enable.cmd still went on timeout during extension deployment.

But increasing the VM size seems to work. I tried _Standard_D4_v3_ successfully today (6 minutes 9 seconds). 

Like I said before: Running enable.cmd from commandline after timeout _always_ works. Is it possible to increase timeout for enable.cmd or to build in a simple retry mechanism to solve this issue?

**Comment by Vasu1105** [comment]
@marco-junge Sorry we currently don't have any option to increase the timeout. And the retry logic won't work since Windows Azure Agent is responsible to run the commands and which is not controlled by extension. 

> > Use "daemon": "task" and set "chef_daemon_interval": "30" (the default setting)
> > Use "daemon": "none" and let your initial run list configure Chef correctly for future run
> 
> Both had no influence and enable.cmd still went on timeout during extension deployment.

Yes this won't work because the installation of chef-client is failed.

**Comment by danielprashanth** [comment]
i also face the same issue , From the logs of command execution i can observe that its not able to download azure chef extension gem and eventually getting timed out. Hence its being killed. After 12 hrs or so , the extension again got downloaded and this time it successfully got installed. But everytime its very tough to wait for so long. Please take up this issue and give a solution asap. Thanks
