### ISSUE TITLE
azure-chef-extension json parse error

### ISSUE THREAD

**Issue by cyprienruelle** [chef-partners/azure-chef-extension#246]
Hello,

We noticed this morning that two of our RHEL 7.4 azure machines have their / filled up with chef-client.log. In this log, we have thousands of errors:

> [2018-04-27T08:18:46+00:00] ERROR: Report handler AzureExtension::StartHandler raised #<JSON::ParserError: 765: unexpected token at ''>
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/azure-chef-extension-0.0.1/lib/chef/azure/heartbeat.rb:33:in `update'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/azure-chef-extension-0.0.1/lib/chef/azure/helpers/shared.rb:136:in `report_heart_beat_to_azure'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/azure-chef-extension-0.0.1/lib/chef/azure/chefhandlers/start_handler.rb:23:in `report_heart_beat'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/azure-chef-extension-0.0.1/lib/chef/azure/chefhandlers/start_handler.rb:17:in `report'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/handler.rb:259:in `run_report_unsafe'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/handler.rb:247:in `run_report_safely'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/handler.rb:101:in `block in run_start_handlers'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/handler.rb:99:in `each'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/handler.rb:99:in `run_start_handlers'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/handler.rb:109:in `block in <class:Handler>'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/client.rb:430:in `block in run_started'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/client.rb:429:in `each'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/client.rb:429:in `run_started'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/client.rb:277:in `run'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:291:in `block in fork_chef_client'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:279:in `fork'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:279:in `fork_chef_client'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:244:in `block in run_chef_client'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:232:in `run_chef_client'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/client.rb:457:in `loop'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/client.rb:457:in `interval_run_chef_client'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/client.rb:441:in `run_application'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:59:in `run'
[2018-04-27T08:18:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/bin/chef-client:26:in `<top (required)>'
[2018-04-27T08:18:46+00:00] ERROR: /bin/chef-client:58:in `load'

 We certainly have some work to do to better handle our logs (logrotate & stuff...) but we'd like to understand why 2 of our 30 machines  display those errors whereas all the others have their azure-chef-extension running correctly.

All machines have been deployed the same way, are the same kind of instances and there is no difference from a network point of view.

Can someone please help us figure out what is going on with our machines?

Thanks in advance.

**Comment by cyprienruelle** [comment]
Few month already passed and the issue is still open.
I guess I got to understand some things a little bit better.

When you create an Azure VM (on our specific case, an RHEL instance), you can ask the installation of the chef extension. This automatically install the azure-chef-extension.
In our case, we never used it.

When a cookbook is running an error, chef-client tries to notify somehow some kind of azure chef server which configuration is described in HandlerEnvironment.json. And that file does not exist... The code 
from `lib/chef/azure/helpers/shared.rb` load it this way:
`
107      handler_env = JSON.parse(File.read("#{chef_extension_root}/HandlerEnvironment.json"))`

And that's why we got an error during the handling of an error...

But...
I still don't understand why it tries to execute that code and I come to that point where I'm thinking of uninstall that azure-chef-extension while keeping chef. 
But I can't guess what are the consequences and if I can do it with chef.

I think about disabling the extension on my vm-creation template but I still have to deal with existing VM.

**Comment by Vasu1105** [comment]
@cyprienruelle sorry for late reply. One of our team member tried reproduce the issue at our end but we not able to reproduce it. We will be happy to help you Could you please tell which commands you are using to install azure-chef-extension. Is it possible for you to share the template that you are using to deploy the vm. Also share all logs file located at

Log files:-
i. /var/log/waagent.log
ii. /var/log/azure/custom.log
iii. var/log/azure/Chef.Bootstrap.WindowsAzure.LinuxChefClient/<extension-version>/CommandExecution.log
output of /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient/<extension-version>/status/*.status

**Comment by cyprienruelle** [comment]
Here it is:
[CommandExecution.log](https://github.com/chef-partners/azure-chef-extension/files/2123932/CommandExecution.log)
[custom.log](https://github.com/chef-partners/azure-chef-extension/files/2123933/custom.log)
[waagent.log](https://github.com/chef-partners/azure-chef-extension/files/2123934/waagent.log)
[0.status.log](https://github.com/chef-partners/azure-chef-extension/files/2123936/0.status.log)

So while looking for the log file, I ran into that HandlerEnvironment.json file into /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient...

guess /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/azure-chef-extension-0.0.1/ is not the right place to look after extensions.
By the way, how can I check chef/azure-extension configuration, I run out of idea to look after config file ?

Thanks for your help.

**Comment by Vasu1105** [comment]
If you are looking after client.rb its in /etc/chef
