### ISSUE TITLE
HTTP Request Returned 403 Forbidden for the first boot

### ISSUE THREAD

**Issue by pennylliang** [chef-partners/azure-chef-extension#66]
Hi,

I am using windows chef extension 1210.12.
OS: 2012R2 with SQL2014
VM size: A2

sometimes, in the first chef boot, I meet the following error:

```
[2015-09-08T08:39:22+00:00] INFO: Chef Client Service initialized
[2015-09-08T08:39:27+00:00] INFO: Next chef-client run will happen in 0.9096172706210285 seconds
[2015-09-08T08:39:28+00:00] INFO: Reconfiguring with startup parameters
[2015-09-08T08:39:32+00:00] INFO: Chef-Client service is starting a chef-client run...
[2015-09-08T08:39:32+00:00] INFO: Starting chef-client in a new process
[2015-09-08T08:39:36+00:00] WARN: Chef client 1592 is running, will wait for it to finish and then run.
# Logfile created on 2015-09-08 08:39:18 +0000 by logger.rb/41954
[2015-09-08T08:39:58+00:00] INFO: *** Chef 12.4.1 ***
[2015-09-08T08:39:58+00:00] INFO: Chef-client pid: 1592
[2015-09-08T08:40:46+00:00] INFO: Client key c:/chef/client.pem is not present - registering
[2015-09-08T08:40:54+00:00] INFO: HTTP Request Returned 403 Forbidden: error
[2015-09-08T08:40:54+00:00] ERROR: Running exception handlers
[2015-09-08T08:40:54+00:00] ERROR: Report handler AzureExtension::ExceptionHandler raised #<NoMethodError: undefined method `name' for nil:NilClass>
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/azure-chef-extension-0.0.1/lib/chef/azure/chefhandlers/exception_handler.rb:21:in `report'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:226:in `run_report_unsafe'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:214:in `run_report_safely'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:118:in `block in run_exception_handlers'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `each'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `run_exception_handlers'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:127:in `block in <class:Handler>'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:428:in `call'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:428:in `block in run_failed'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:427:in `each'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:427:in `run_failed'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:296:in `rescue in run'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:306:in `run'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:229:in `block in run_chef_client'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:375:in `run_application'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/bin/chef-client:67:in `load'
[2015-09-08T08:40:54+00:00] ERROR: C:/opscode/chef/bin/chef-client:67:in `<main>'
[2015-09-08T08:40:54+00:00] ERROR: Exception handlers complete
[2015-09-08T08:40:54+00:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2015-09-08T08:40:54+00:00] FATAL: Net::HTTPServerException: 403 "Forbidden"
[2015-09-08T08:41:05+00:00] INFO: *** Chef 12.4.1 ***
[2015-09-08T08:41:05+00:00] INFO: Chef-client pid: 3672
[2015-09-08T08:41:35+00:00] INFO: Client key c:/chef/client.pem is not present - registering
[2015-09-08T08:41:36+00:00] INFO: HTTP Request Returned 404 Object Not Found: error
[2015-09-08T08:41:37+00:00] INFO: Run List is []
[2015-09-08T08:41:37+00:00] INFO: Run List expands to []
[2015-09-08T08:41:37+00:00] INFO: Starting Chef Run for sqlvm0.AutoRG.net
[2015-09-08T08:41:37+00:00] INFO: Running start handlers
[2015-09-08T08:41:37+00:00] INFO: Loading Handler environment...
[2015-09-08T08:41:37+00:00] INFO: C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.4.1000\RuntimeSettings --> C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.4.1000\Status --> C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.4.1000\Status\HeartBeat.Json --> C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.4.1000
[2015-09-08T08:41:37+00:00] INFO: Status file name: C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.4.1000\Status/0.status
[2015-09-08T08:41:37+00:00] INFO: Reporting heartbeat...
[2015-09-08T08:41:37+00:00] INFO: Start handlers complete.
[2015-09-08T08:41:37+00:00] INFO: HTTP Request Returned 404 Not Found: 
[2015-09-08T08:41:37+00:00] INFO: Loading cookbooks []
[2015-09-08T08:41:37+00:00] WARN: Node sqlvm0.AutoRG.net has an empty run list.
[2015-09-08T08:41:37+00:00] INFO: Chef Run complete in 0.738975 seconds
[2015-09-08T08:41:37+00:00] INFO: Running report handlers
[2015-09-08T08:41:37+00:00] INFO: Loading Handler environment...
[2015-09-08T08:41:37+00:00] INFO: C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.4.1000\RuntimeSettings --> C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.4.1000\Status --> C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.4.1000\Status\HeartBeat.Json --> C:\WindowsAzure\Logs\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.4.1000
[2015-09-08T08:41:37+00:00] INFO: Status file name: C:\Packages\Plugins\Chef.Bootstrap.WindowsAzure.ChefClient\1210.12.4.1000\Status/0.status
[2015-09-08T08:41:37+00:00] INFO: Reporting heartbeat...
[2015-09-08T08:41:37+00:00] INFO: Report handlers complete
[2015-09-08T08:41:45+00:00] INFO: Child process exited (pid: 3360)
[2015-09-08T08:41:45+00:00] INFO: Next chef-client run will happen in 1800.0805891492241 seconds
[2015-09-08T09:11:47+00:00] INFO: Reconfiguring with startup parameters
[2015-09-08T09:11:51+00:00] INFO: Chef-Client service is starting a chef-client run...
[2015-09-08T09:11:52+00:00] INFO: Starting chef-client in a new process
```

Stacktrace file:

```
Generated at 2015-09-08 08:40:54 +0000
Net::HTTPServerException: 403 "Forbidden"
C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http/response.rb:119:in `error!'
C:/opscode/chef/embedded/apps/chef/lib/chef/http.rb:145:in `request'
C:/opscode/chef/embedded/apps/chef/lib/chef/http.rb:126:in `post'
C:/opscode/chef/embedded/apps/chef/lib/chef/api_client/registration.rb:93:in `create'
C:/opscode/chef/embedded/apps/chef/lib/chef/api_client/registration.rb:84:in `create_or_update'
C:/opscode/chef/embedded/apps/chef/lib/chef/api_client/registration.rb:57:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:608:in `register'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:253:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:229:in `block in run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:375:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:67:in `load'
C:/opscode/chef/bin/chef-client:67:in `<main>'
```

The second boot is OK, but as you know the RUN LIST will expands to empty, and this cause my deployment fail. I deploy 105 VM with chef extension, 7 VM meet this issue.

Please help to check. Thank you.

**Comment by prrice79** [comment]
@pennylliang I know this is old... however, we're running into this. Curious if you were able to resolve it, and how?

Thanks!

**Comment by pennylliang** [comment]
@prrice79 , sorry, we do not have solution for this, maybe https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview scale set is a workaround, there is an option - "overprovision": "true" in this template, please keep it as true or remove this line (default value is true). If you remove that line or set it as true, behind the scenes this will create a small percentage of additional VMs and then return the first ones that hit a ready state.  This means the VMs will likely not all be sequentially numbered (not sure if that matters), but if it is the case that you were in general losing only one VM then you will see the overall rate of success rise.
hope this helps.

**Comment by Vasu1105** [comment]
@prrice79 most of the time its chef-server permission issues https://docs.chef.io/errors.html.

**Comment by Vasu1105** [comment]
Closing this as its very old.
